# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NoBlackMagic.com
email: marco.pegoraro@gmail.com
description: Personal blog about my professional experience as web passionate guy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://NoBlackMagic.com" # the base hostname & protocol for your site
basepath: "/"
twitter_username: thepeg
github_username:  marcopeg

# Build settings
markdown: kramdown
